"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const graphController_1 = require("../controllers/graphController");
const router = (0, express_1.Router)();
router.get('/view-graph', graphController_1.viewGraph);
router.get('/node-metadata', graphController_1.getNodeMetadata);
router.get('/generate-questions-with-answers', graphController_1.generateQuestionsWithAnswers);
router.post('/verify-answer', graphController_1.verifyAnswer);
router.post('/generate-conversation-response', graphController_1.generateConversationResponse);
router.get('/user/profile', graphController_1.getUserProfile);
router.get('/search-graph', graphController_1.searchGraph);
router.get('/semantic-search-graph', graphController_1.semanticSearchGraph);
exports.default = router;
