"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const multer_1 = __importDefault(require("multer"));
const practiceExamController_1 = require("../controllers/practiceExamController");
const router = (0, express_1.Router)();
const upload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 1, fields: 2 } });
router.use(practiceExamController_1.requirePracticeExamUser);
router.post('/', upload.single('practice_exam'), (0, practiceExamController_1.route)(practiceExamController_1.generate));
router.get('/', (0, practiceExamController_1.route)(practiceExamController_1.list));
router.get('/:examId', (0, practiceExamController_1.route)(practiceExamController_1.get));
router.post('/:examId/attempts', (0, practiceExamController_1.route)(practiceExamController_1.createAttempt));
router.get('/:examId/attempts', (0, practiceExamController_1.route)(practiceExamController_1.listAttempts));
router.get('/:examId/attempts/:attemptId', (0, practiceExamController_1.route)(practiceExamController_1.getAttempt));
router.patch('/:examId/attempts/:attemptId', (0, practiceExamController_1.route)(practiceExamController_1.saveDraft));
router.post('/:examId/attempts/:attemptId/submit', (0, practiceExamController_1.route)(practiceExamController_1.submit));
router.use(practiceExamController_1.practiceExamError);
exports.default = router;
